### ISSUE TITLE
Use state instead of new fetch on single hike page

### ISSUE THREAD

**Issue by srietkerk** [MaggieYang57/CSC308-TeamB#80]
Estimated time: 3 hours

**Comment by sky-kurth** [comment]
1: Still in progress

**Comment by Baagi** [comment]
This might have been fixed in this commit: https://github.com/MaggieYang57/CSC308-TeamB/commit/5a7ea6ce2a1856c3946efdeecdaae38c0fd0145e 

Now it fetches only once for the that hike id and sets it as the state:
 https://github.com/MaggieYang57/CSC308-TeamB/blob/5a7ea6ce2a1856c3946efdeecdaae38c0fd0145e/frontend/src/SinglePage.js#L24-L34
